# INSTALL
FROM node:22.16.0-alpine AS jigpuzzle-installer-remote
LABEL jigpuzzle-installer-remote=true

RUN apk update \
    && apk upgrade -f \
    && apk add -f zip

WORKDIR /build
COPY package.json package-lock.json ./
COPY ./src/server/package.json ./src/server/package.json
COPY ./src/client/package.json ./src/client/package.json
COPY ./src/shared/package.json ./src/shared/package.json

RUN npm install --omit=dev
RUN npm install -ws --omit=dev
RUN mv ./node_modules /tmp/node_modules_prod
RUN npm install
RUN npm install -ws


# BUILD TYPESCRIPT AND WEBPACK STUFF
FROM jigpuzzle-installer-remote AS jigpuzzle-builder-remote
LABEL jigpuzzle-installer-remote=false
LABEL jigpuzzle-build-builder-remote=true
WORKDIR /build
COPY . .

RUN npm run build


# COPY BUILT FILES INTO NEW IMAGE (WITH ORIGINAL SOURCE CODE)
# INCLUDE scripts/ AND db/ FOR RUNTIME MANAGEMENT (DB PATCHES AND VARIOUS CONVENIENCE SCRIPTS)
FROM jigpuzzle-builder-remote AS jigpuzzle-app-remote
LABEL jigpuzzle-build-installer=false
LABEL jigpuzzle-build-builder=false

WORKDIR /app
COPY --from=jigpuzzle-builder-remote /build/dist ./dist
COPY --from=jigpuzzle-builder-remote /build/package.json /build/package-lock.json ./
COPY --from=jigpuzzle-builder-remote /tmp/node_modules_prod ./node_modules

# GET ZIP READY

#RUN zip --help #zip -r /output/build.zip /app/dist
CMD ["zip", "-r", "/output/build.zip", "/app/dist"]
#CMD ["npm", "start"]
